export let products = [
  {
    title: "Don pascual cabernet 750ml",
    price: 490,
    stock: 17,
    description: "Vino uruguayo de primer nivel. Cabernet sauvignon.",
    category: "vinos",
    img: "https://res.cloudinary.com/dn6wz2clp/image/upload/v1687383675/vino-don-pascual-varietal-cabernet-sauvignon-750ml-vino-don-pascual-varietal-cabernet-sauvignon-750ml_zxrcgp.jpg",
  },
  {
    title: "Don pascual rosado 750ml",
    price: 490,
    stock: 13,
    description: "Vino uruguayo de primer nivel. Rosado",
    category: "vinos",
    img: "https://res.cloudinary.com/dn6wz2clp/image/upload/v1687384077/Brut-Blanc-de-noirs-t_hwrltb.jpg",
  },
  {
    title: "Don pascual blanco 750ml",
    price: 590,
    stock: 21,
    description: "Vino blanco uruguayo de primer nivel",
    category: "vinos",
    img: "https://res.cloudinary.com/dn6wz2clp/image/upload/v1687383725/Brut-Blanc-de-Blancs-t_nge9wg.jpg",
  },
  {
    title: "Johnnie walker red label 750ml",
    price: 950,
    stock: 38,
    description: "Johnnie walker etiqueta roja.",
    category: "destilados",
    img: "https://res.cloudinary.com/dn6wz2clp/image/upload/v1687384050/johnnie-750_fzcvta.webp",
  },
  {
    title: "Johnnie walker black label 750ml",
    price: 1890,
    stock: 27,
    description: "Johnnie walker etiqueta negra",
    category: "destilados",
    img: "https://res.cloudinary.com/dn6wz2clp/image/upload/v1687383796/15949502775326_rpuzik.png",
  },
  {
    title: "Cerveza Heineken 473ml",
    price: 109,
    stock: 86,
    description: "Cerveza importada en lata",
    category: "cervezas",
    img: "https://res.cloudinary.com/dn6wz2clp/image/upload/v1688851348/image-removebg-preview_qlwmv9.png",
  },
  {
    title: "Cerveza Heineken 970ml",
    price: 189,
    stock: 91,
    description: "Cerveza importada en botella",
    category: "cervezas",
    img: "https://res.cloudinary.com/dn6wz2clp/image/upload/v1688851575/image-removebg-preview_1_ywc7ky.png",
  },
  {
    title: "Concha y toro cabernet sauvignon",
    price: 279,
    stock: 3,
    description: "Vino chileno importado. De los mejores del mundo.",
    category: "vinos",
    img: "https://res.cloudinary.com/dn6wz2clp/image/upload/v1690222546/607467_jlxjgj.jpg",
  },
  {
    title: "Concha y toro rosado",
    price: 279,
    stock: 0,
    description: "Vino chileno importado. De los mejores del mundo.",
    category: "vinos",
    img: "https://res.cloudinary.com/dn6wz2clp/image/upload/v1690222612/607466-1_rs26ty.jpg",
  },
  {
    title: "Ron barcardi 750ml",
    price: 589,
    stock: 7,
    description: "Ron cubano de la mejor calidad.",
    category: "destilados",
    img: "https://res.cloudinary.com/dn6wz2clp/image/upload/v1690222676/542863_xxi62l.jpg",
  },
  {
    title: "Fernet branca 750ml",
    price: 449,
    stock: 19,
    description: "Bebida de tradición italiana.",
    category: "destilados",
    img: "https://res.cloudinary.com/dn6wz2clp/image/upload/v1690222793/541240_ahozjr.jpg",
  },
  {
    title: "Cerveza schneider 473ml",
    price: 79,
    stock: 86,
    description: "Cerveza importada en lata.",
    category: "cervezas",
    img: "https://res.cloudinary.com/dn6wz2clp/image/upload/v1690222885/P395258-1_zxlzyt.jpg",
  },
  {
    title: "cerveza schenider 970ml",
    price: 129,
    stock: 43,
    description: "Cerveza importada en botella.",
    category: "cervezas",
    img: "https://res.cloudinary.com/dn6wz2clp/image/upload/v1690222957/1837623922_w0zaup.jpg",
  },
];
